services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./backend/docker/php-fpm
      dockerfile: ./Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/var/www/backend

  backend-nginx:
    build:
      context: ./backend/docker/nginx
      dockerfile: ./Dockerfile
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./backend:/var/www/backend
    depends_on:
      - php-fpm

  postgres:
    build:
      context: ./backend/docker/postgres
      dockerfile: ./Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  node:
    build:
      context: ./frontend/docker/node
      dockerfile: ./Dockerfile
    volumes:
      - ./frontend:/frontend
    tty: true

  frontend-nginx:
    build:
      context: ./frontend/docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/var/www/frontend
    depends_on:
      - php-fpm
    ports:
      - ${FRONTEND_NGINX_PORT}:80

volumes:
  db_data: