services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./docker/php-fpm
      dockerfile: ./Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/app

  backend-nginx:
    build:
      context: ./docker/nginx
      dockerfile: ./Dockerfile
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./:/var/www/app
    depends_on:
      - php-fpm

  postgres:
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db_data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db_data: